jobs:
- name: job-upload-release
  plan:
  - get: source-code
    params:
      depth: 1
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: source-code
      platform: linux
      run:
        path: source-code/nginx_release/ci/tasks/upload-release.sh
    task: upload-release
  - config:
      image_resource:
        source:
          repository: starkandwayne/concourse
        type: docker-image
      inputs:
      - name: source-code
      platform: linux
      run:
        path: source-code/nginx_release/ci/tasks/deploy-release.sh
    task: deploy-release
  public: true
meta:
  name: russTbaker-nginx-demo
  pipeline: russTbaker-nginx-demo
  target: training
  url: https://pipes.starkandwayne.com
resources:
- name: source-code
  source:
    branch: master
    uri: https://github.com/russTbaker/sw-concourse-training.git
  type: git

